BAM.UI/Controllers/BasketController.cs
using BAM.Business.Abstract;
using BAM.UI.Models;
using BAM.UI.Models.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BAM.UI.Controllers
{
    [Authorize(Roles = "Member")]
    public class BasketController : Controller
    {
        IBookService _bookService;

        public BasketController(IBookService bookService)
        {
            _bookService = bookService;
        }

        public IActionResult Index()
        {
            var book = SessionHelpers.GetObjectFromJson<List<BookBasketViewModel>>(HttpContext.Session, "book");
            if (book == null)
                return View();

            ViewBag.Total = book.Sum(i => i.Book.Price * i.Quantity);

            return View(book);
        }

        public IActionResult Buy(int id)
        {
            if (SessionHelpers.GetObjectFromJson<List<BookBasketViewModel>>(HttpContext.Session, "book") == null)
            {
                var Book = new List<BookBasketViewModel>();
                Book.Add(new BookBasketViewModel
                {
                    Book = _bookService.Get(id),
                    Quantity = 1
                });
                SessionHelpers.SetObjectAsJson(HttpContext.Session, "book", Book);
            }
            else
            {
                var Book = SessionHelpers.GetObjectFromJson<List<BookBasketViewModel>>(HttpContext.Session, "book");
                int index = isExits(Book, id);
                if(index == -1)
                {
                    Book.Add(new BookBasketViewModel
                    {
                        Book = _bookService.Get(id),
                        Quantity = 1
                    });
                }
                else
                {
                    Book[index].Quantity++;
                }
                SessionHelpers.SetObjectAsJson(HttpContext.Session, "book", Book);
            }
            return RedirectToAction("Index");
        }

        public IActionResult Remove(int id)
        {
            var Book = SessionHelpers.GetObjectFromJson<List<BookBasketViewModel>>(HttpContext.Session, "book");
            int index = isExits(Book, id);
            Book.RemoveAt(index);
            SessionHelpers.SetObjectAsJson(HttpContext.Session, "book", Book);
            return RedirectToAction("Index");
        }

        private int isExits(List<BookBasketViewModel> Book, int id)
        {
            for (int i = 0; i < Book.Count; i++)
            {
                if (Book[i].Book.Id.Equals(id))
                {
                    return i;
                    break;
                }
            }
            return -1;
        }
    }
}

BAM.UI/Controllers/BookController.cs
using BAM.Business.Abstract;
using BAM.Entities.Concrete;
using BAM.UI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BAM.UI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BookController : Controller
    {
        IBookService _bookService;
        ICategoryService _categoryService;

        public BookController(IBookService bookService, ICategoryService categoryService)
        {
            _bookService = bookService;
            _categoryService = categoryService;
        }
        public IActionResult Index()
        {
            var books = _bookService.GetAll();
            return View(books);
        }

        public IActionResult Add(AddBookViewModel p)
        {
            p = new();
            p.categories = _categoryService.GetAll();
            return View(p);
        }

        [HttpPost]
        public IActionResult Add(AddBookViewModel p,string category)
        {
            p.book.Status = true;
            p.categories = _categoryService.GetAll();
            var addedCategory = _categoryService.GetByCategoryName(category);
            p.book.CategoryId = addedCategory.Id;
            _bookService.Add(p.book);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(AddBookViewModel p,int id)
        {
            p = new();
            p.categories = _categoryService.GetAll();
            p.book = _bookService.Get(id);
            var category = _categoryService.Get(p.book.CategoryId);
            ViewBag.Selected = category.Name;
            return View(p);
        }

        [HttpPost]
        public IActionResult Edit(AddBookViewModel p)
        {
            var category = _categoryService.GetByCategoryName(p.book.Category.Name);
            p.book.CategoryId = category.Id;
            p.book.Status = true;
            _bookService.Update(p.book);
            return RedirectToAction("Index");
        }

        public IActionResult ChangeStatus(int id)
        {
            var book = _bookService.Get(id);
            if (book.Status)
            {
                book.Status = false;
            }
            else
            {
                book.Status = true;
            }
            _bookService.Update(book);
            return RedirectToAction("Index");
        }
    }
}

BAM.UI/Controllers/CategoryController.cs
using BAM.Business.Abstract;
using BAM.Entities.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BAM.UI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public IActionResult Index()
        {
            var categories = _categoryService.GetAll();
            return View(categories);
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Category category)
        {
            _categoryService.Add(category);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var category = _categoryService.Get(id);
            return View(category);
        }

        [HttpPost]
        public IActionResult Edit(Category category)
        {
            _categoryService.Update(category);
            return RedirectToAction("Index");
        }
    }
}

BAM.UI/Views/Shared/_BasketPartial.cshtml
@foreach (var item in Model)
{
    <div class="card mb-3">
        <div class="card-body">
            <div class="d-flex justify-content-between">
                <div class="d-flex flex-row align-items-center">
                    <div>
                        <img src="@item.Book.Image"
                         class="img-fluid rounded-3" alt="Shopping item" style="width: 65px;">
                    </div>
                    <div class="ms-3">
                        <h5><a class="text-decoration-none text-dark" asp-action="Details" asp-controller="Home" asp-route-id="@item.Book.Id">@item.Book.Name</a></h5>
                        <hr>
                        <p class="small mb-0">@item.Book.Author</p>
                    </div>
                </div>
                <div class="d-flex flex-row align-items-center">
                    <div style="width: 50px;">
                        <h5 class="fw-normal mb-0">@item.Quantity</h5>
                    </div>
                    <div style="width: 80px;">
                        <h5 class="mb-0">@(item.Book.Price * item.Quantity) ₺</h5>
                    </div>
                    <a asp-action="Remove" asp-controller="Basket" asp-route-id="@item.Book.Id" style="color: #cecece;"><i class="fas fa-trash-alt"></i></a>
                </div>
            </div>
        </div>
    </div>
}

BAM.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

    <title>BAM Library</title>
</head>

<body style="background-color: #EEEAEA;">
    <div style="background-color:#9C0C13">
        <nav class="navbar navbar-expand-lg container" >

            <div class="container-fluid">

                <a class="navbar-brand" style="color:white" href="/home/index">BAM Library</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @if (User.Identity.IsAuthenticated)
                {
                    @if (User.IsInRole("Admin"))
                    {
                        <a class="nav-link active" style="color:white" aria-current="page" asp-action="Index" asp-controller="Book">Book</a>
                        <a class="nav-link active" style="color:white" aria-current="page" asp-action="GetRole" asp-controller="Admin">Role</a>
                        <a class="nav-link active" style="color:white" aria-current="page" asp-action="Index" asp-controller="Category">Category</a>
                        <div class="float-end">
                            <button class="btn me-2" style="background-color:#171717; color:white;">@User.Identity.Name</button>
                            <a class="btn" style="background-color:#171717; color:white;" asp-action="LogOut" asp-controller="Account">Log Out</a>

                        </div>
                    }
                    else
                    {
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" style="color:white" aria-current="page" href="/home/books">Books</a>
                            </li>
                        </ul>
                        <form class="d-flex" asp-action="Index" asp-controller="Home" role="search" method="post">
                            <input name="description" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn me-2" style="background-color:#171717; color:white;" type="submit">Search</button>
                        </form>
                        <div class="float-end">
                            <button class="btn me-2" style="background-color:#171717; color:white;">@User.Identity.Name</button>
                            <a class="btn" style="background-color:#171717; color:white;" asp-action="LogOut" asp-controller="Account">Log Out</a>
                            <a asp-action="Index" asp-controller="Basket" class="btn" style="background-color:#171717;color:white"><i class="bi bi-cart3"></i></a>
                        </div>
                    }
                }
                else
                {
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" style="color:white" aria-current="page" href="/home/books">Books</a>
                        </li>
                    </ul>
                    <form class="d-flex" asp-action="Index" asp-controller="Home" role="search" method="post">
                        <input name="description" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn me-2" style="background-color:#171717; color:white;" type="submit">Search</button>
                    </form>
                    <a class="btn" style="background-color:#171717; color:white;" method="get" asp-action="Login" asp-controller="Account">Log in</a>
                    <a class="btn ms-2" style="background-color:#171717; color:white;" method="get" asp-action="SignUp" asp-controller="Account">Sign Up</a>
                }
            </div>
        </nav>
    </div>
    <main class="p-4">
        @RenderBody()
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>